### ISSUE TITLE
Copy link to clipboard doesn't work for shareable links

### ISSUE THREAD

**Issue by dzucconi** [arenahq/ervell#106]
![](http://static.damonzucconi.com/_capture/ef/vr9b6wpkgss00.png)

**Comment by dzucconi** [comment]
(Would probably be a lot simpler to just have an onclick select of the field (See Artsy's share menu))

**Comment by broskoski** [comment]
++ thx, yeah would like to avoid including an swf in this repo if at all possible

**Comment by danpia** [comment]
+
