### ISSUE TITLE
I saw a red (private) channel in one of my channels

### ISSUE THREAD

**Issue by msutherl** [arenahq/ervell#109]
This channel popped up in my Accelerationism channel: https://www.are.na/angela-gabereau/t**********x. Box was red, when I clicked I got a 404 and when I refreshed it disappeared.

**Comment by danpia** [comment]
Likely someone accidentally connected a private channel to one of your channels while you were in it, we might address the architecture causing this to happen in future but it isn't a privacy bug. Closing for now
