### ISSUE TITLE
Load low resolution previews, or progressive JPEGs preemptively

### ISSUE THREAD

**Issue by msutherl** [arenahq/ervell#111]
Find myself loading a channel, then scroll, then wait for too long to see anything. Would be nice to see low resolution previews or for images to start loading before I scroll to them somehow so I can orient myself quicker.

**Comment by msutherl** [comment]
http://blog.patrickmeenan.com/2013/06/progressive-jpegs-ftw.html

**Comment by broskoski** [comment]
We use an image proxy to get different image sizes on the fly. Generating a progressive JPEG on request right now looks like too technically difficult for the very subtle wins.
