### ISSUE TITLE
Flex-box weirdness with fourth block in collection

### ISSUE THREAD

**Issue by broskoski** [arenahq/ervell#15]
![screen shot 2015-02-12 at 11 37 55 pm](https://cloud.githubusercontent.com/assets/821469/6182356/512ad582-b310-11e4-811b-72c7a2040b94.png)
![screen shot 2015-02-12 at 11 40 32 pm](https://cloud.githubusercontent.com/assets/821469/6182368/803c4036-b310-11e4-8c10-91be6c87fe22.png)

**Comment by danpia** [comment]
@broskoski it's 1px of the channel border I think, but I'll optimize the flex properties (which we weren't really using)
