### ISSUE TITLE
Safari Pinned Tabs 'favicon.svg' inclusion

### ISSUE THREAD

**Issue by edouerd** [arenahq/ervell#153]
Here's what Arena's pinned tab looks like right now (for the Safari users out there):

<img width="112" alt="screen shot 2015-10-10 at 12 14 38 am" src="https://cloud.githubusercontent.com/assets/1195363/10409388/23adcba6-6ee4-11e5-9374-48ac28e84959.png">

This is an easy fix!

Just insert this where it's needed in the head:

```
<link rel="mask-icon" href="website_icon.svg" color="red">
```

Complete usage is documented here: 

https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html

Glad y'all actually have your work open sourced, been trying to call attention to this to other products I use out there, and it's not so easy ~_~

Bye!

**Comment by danpia** [comment]
Thanks, I noticed the pinned favicon too, will add it.

**Comment by danpia** [comment]
coming in next deployment
