### ISSUE TITLE
unsolicited design input — block previewing

### ISSUE THREAD

**Issue by edouerd** [arenahq/ervell#217]
Hi! 

I want to begin that I'm posting this issue up not as a request, or as a nitpick of any kind, or as a jab in any way — I'm simply a huge fan of Arena and had some free time to mock up an idea that popped into my head while browsing through blocks.

-

![1 feed](https://cloud.githubusercontent.com/assets/1195363/13903670/a583cc42-ee5b-11e5-9143-7789d0691952.png)

##### Feed
This view is totally the same, in this userflow, I'm simply clicking into one of the blocks...

-

![2 connections](https://cloud.githubusercontent.com/assets/1195363/13903673/cf375a18-ee5b-11e5-84c5-06f3575c0c7a.png)

##### Image preview, initial view
This is obviously where things diverge from what currently exists. In a nutshell, this is an approach to surface more information all at once, while keeping the context of the original block image/text/embed/etc. —

-

![3 convo](https://cloud.githubusercontent.com/assets/1195363/13903691/98f9f018-ee5c-11e5-9996-a57ea6e6846d.png)

##### Image preview, comments 
— as Arena exists right now, a user needs to scroll down in order to view any discourse happening around a block, and scroll all the way back up if they need to re-reference the block being discussed. 

In this alternative interface structure, a user can view the block's info/source, whatever comments are being added to the image, and the block itself — all at once. 

-

I'd like to imagine that this (or something like it) would make blocks slightly more navigable and easier to consume, but hey, it's just one idea of many!

Love the work you all are doing! Peace!

**Comment by danpia** [comment]
Hi, thanks for the design feedback, more than welcome. 
Actually your suggestion looks pretty close to an old Are.na iteration, with the latest design we decided to go for a "content only" approach in the lightbox and avoid a cluttered screen (especially on smaller ones).

It's far from perfect, i.e. we already realized that it's frustrating having to click the Connections tab very often, so we'll try some design changes or merging in there. 

Feel free to send us feedback or comments any time.
ps.: I'm adding your mockup to our design ideas/references and closing this issue.
