### ISSUE TITLE
Ordered list (<ol>) elements not rendering in lightbox view

### ISSUE THREAD

**Issue by edouerd** [arenahq/ervell#222]
Here's a block I formatted with numbered ordering, viewed from a channel:
<img width="439" alt="screen shot 2016-04-15 at 10 21 40 pm" src="https://cloud.githubusercontent.com/assets/1195363/14578546/b0c97234-0358-11e6-9f89-56c30c55fc19.png">

Here's the same block expanded into lightbox view:
<img width="423" alt="screen shot 2016-04-15 at 10 21 45 pm" src="https://cloud.githubusercontent.com/assets/1195363/14578547/c633d24a-0358-11e6-9238-5f33b09f62db.png">

When clicked into to edit, it renders fine:
<img width="402" alt="screen shot 2016-04-15 at 10 24 20 pm" src="https://cloud.githubusercontent.com/assets/1195363/14578553/d7348058-0358-11e6-81e6-c8cbb157cf53.png">

Cheers!

**Comment by danpia** [comment]
thanks, will fix
