### ISSUE TITLE
Bookmarklet: Broken styling

### ISSUE THREAD

**Issue by edouerd** [arenahq/ervell#227]
How it appeared by default:

<img width="360" alt="screen shot 2016-06-04 at 3 51 59 pm" src="https://cloud.githubusercontent.com/assets/1195363/15801742/a77d1c5e-2a6c-11e6-8887-af67c7c3d260.png">

How it appeared after drag-n-drop of an image:

![screen shot 2016-06-04 at 3 51 38 pm](https://cloud.githubusercontent.com/assets/1195363/15801747/b20a5e20-2a6c-11e6-9089-35c8252b4e52.png)

Seems to be broken everywhere I go!

—

OSX Chrome: Version 50.0.2661.102 (64-bit)

**Comment by broskoski** [comment]
Thanks @edouerd! Will fix.

**Comment by broskoski** [comment]
Thanks @edouerd! Will fix.
