### ISSUE TITLE
User can't follow or unfollow people and channels on beta

### ISSUE THREAD

**Issue by danpia** [arenahq/ervell#23]
http://beta.are.na/roberto-medri sees "follow username" if he goes on any profile, both for people he's already following or not. He clicks follow and nothing happens, not even the feedback of toggling into "unfollow". Same for channels, he clicks and nothing happens nor feedback.

He sent me screenshots and he tried to unfollow me without success, doesn't look like a mistake of his.

**Comment by broskoski** [comment]
Gonna close this until there is another case or we can reproduce
