### ISSUE TITLE
list view QA / quicktweaks

### ISSUE THREAD

**Issue by csherron** [arenahq/ervell#242]
- [x] 20px left/right padding on thumbnails
- [x] title width can be like 500px
- [ ] add field should expand with text
- [x] text-cursor is extra-big (full height) in the add field
- [x] remove "updated" from timestamps, unecessary
- [x] use dotted line for rows that still need to load up
- [x] match link icon size to video icon size
- [x] make link icon color lighter so that hover state is more obvious
- [x] give video icon a hover state
- [x] move view toggle to the right of "+ new channel"
- [x] scroll location after lightbox usage still reflects block mode position i think
- [ ] loading big channels and scrolling a lot makes my browser hang up / makes everything disappear and all arena windows inoperative (could also be my shitty internet)
- [x] tried searching 'youtube' in a channel and it didn't really filter anything at all (edited)
- [x] new order:
  1. add field
  2. in-channel search
  3. column IDs
  4. content
- [x] follow button shouldn't show up in your own channels
- [x] on profile seems it loads only two set of pagination
- [x] premium search works on channels but not on profile
- [x] thumbnails overlap w/ title after shrinking browser window 
- [x] link source button doesn't work on premium-search filtered results (like in normal view)
- [x] put trash can icon to the right of block title, change check mark to X
- [x] clicking the thumbnail / list dropdown should toggle between both views (without needing to select individual links on dropdown)
- [x] some channels don't have "follow" next to them (seeing it when i display all of my own channels on profile)
- [x] channels have a pencil icon when there's nothing to edit

**Comment by broskoski** [comment]
Closing, added issues for the remaining items.
