### ISSUE TITLE
new notifications quicktweaks

### ISSUE THREAD

**Issue by danpia** [arenahq/ervell#246]
- [x] the text is red but not the [1] icon (see image)
- [x] cursor: pointer; should only be on the links inside the notification, not the whole area otherwise people will try to open it clicking
- [x]  some names break the line weirdly (see martin murphy in image)
- [x]  [1] stays after I seen the dropdown, closed browser tab, came back. But I didn't click 'All notifications'

![unspecified-2](https://cloud.githubusercontent.com/assets/3718189/17463124/97e36b24-5c8d-11e6-912c-857790d10910.png)

- [x] activating list / thumbnail view while in feed brings you to notifications, not back to feed 
- [x] thumbnail view button / list view button / all notifications button - use lighter gray so hover state is more obvious
- [x] match padding between icons in top bar (space between new channel / view mode / notifs are too large, match w/ space between notifs / avatar)
- [x] Needs empty state

**Comment by csherron** [comment]
activating list / thumbnail view while in feed brings you to notifications, not back to feed

**Comment by csherron** [comment]
thumbnail view button / list view button / all notifications button - use lighter gray so hover state is more obvious

**Comment by csherron** [comment]
match padding between icons in top bar (space between new channel / view mode / notifs are too large, match w/ space between notifs / avatar)

**Comment by broskoski** [comment]
- [ ] Needs empty state

**Comment by csherron** [comment]
<img width="292" alt="screen shot 2016-08-12 at 6 33 10 pm" src="https://cloud.githubusercontent.com/assets/3780330/17651982/d2aeaa90-623f-11e6-91d9-6108256b6356.png">

**Comment by csherron** [comment]
remove notifications subsection from user dropdown

**Comment by danpia** [comment]
- [ ] the space between the icon and dropdown should be padding not empty, if you move the mouse from icon to drowdown not fast enough it closes 
https://www.dropbox.com/s/dje034yttry1lrn/Screenshot%202016-08-15%2001.59.15.png?dl=0
