### ISSUE TITLE
Login Not Working, Returning [Object object] Error

### ISSUE THREAD

**Issue by edouerd** [arenahq/ervell#34]
Attempting to sign in, form is rendering like so:

![screen shot 2015-04-07 at 3 23 34 pm](https://cloud.githubusercontent.com/assets/1195363/7032722/3411c664-dd3a-11e4-88f7-360db74d4dd3.png)
 
Browser Info:

![screen shot 2015-04-07 at 3 25 18 pm](https://cloud.githubusercontent.com/assets/1195363/7032733/51b66c74-dd3a-11e4-9677-d2f172efffd7.png)

**Comment by edouerd** [comment]
Interestingly enough, mobile login seems to work perfectly:

![loginissue](https://cloud.githubusercontent.com/assets/1195363/7033420/879298c2-dd3f-11e4-8488-4430cceae976.gif)

**Comment by broskoski** [comment]
Thanks @edouerd, but can't reproduce! Any other hints?

**Comment by edouerd** [comment]
Login appears to be working for me after resetting my password on a mobile device. Weird!

Nevermind then. :sleepy:

**Comment by broskoski** [comment]
Interesting. Gonna close for now, but please feel free to log any more bugs you come across :ok_hand:
