### ISSUE TITLE
Search results can't be clicked, or need 2-3 clicks before the channel opens

### ISSUE THREAD

**Issue by danpia** [arenahq/ervell#6]
https://www.dropbox.com/s/tuhbzfjkv56fvn8/Screenshot%202015-01-25%2011.12.40.png?dl=0
https://www.dropbox.com/s/ax4olvow2bpergv/Screenshot%202015-01-23%2000.42.02.png?dl=0

**Comment by broskoski** [comment]
I can't reproduce this issue, any tips?

**Comment by danpia** [comment]
seems so random, right now I can reproduce by going to a profile (tested both mine and yours) -> search for "sa" -> click the first result (savour pairing) -> nothing happens, repeatedly.

I'm on Chrome 40.0.2214.91

**Comment by danpia** [comment]
when it happens this error appears in the console as soon as click the search field, I don't even need to type or click the result  https://www.dropbox.com/s/mxebcbrs1yfov93/Screenshot%202015-01-25%2018.36.07.png?dl=0

**Comment by broskoski** [comment]
Fixed in https://github.com/arenahq/ervell/commit/12a92664db89ba2fd06c3f7e1c252c1868a6f6df
