### ISSUE TITLE
Redirect old URLs

### ISSUE THREAD

**Issue by dzucconi** [arenahq/ervell#80]

**Comment by dzucconi** [comment]
Still broken for blocks. URLs take form of:

`https://www.are.na/:channel_id/show/:block_id`

**Comment by broskoski** [comment]
Did a bare minimum fix for this in https://github.com/arenahq/ervell/commit/f1b6a946c68538f6dae28c55fd5410a4bb0d62f1 . As far as I know the only place that links to blocks like this is the bookmarklet, and the previous commit redirects to the channel (where the block will be at the top of the channel). Will address this properly when we redo the bookmarklet shortly but closing for now.
