### ISSUE TITLE
@mentions

### ISSUE THREAD

**Issue by danpia** [arenahq/ervell#82]

**Comment by broskoski** [comment]
Working idea is:
-  `@username` triggers a dropdown / search field, which autocompletes to a user.
- on user select, the username displays as a link to profile (possibly with a mini avatar?)
- the user mentioned receives a notification that they were mentioned in a comment (should this notification appear in the normal feed as well?).

Variation for channels could be:
- Same as above but `*channel`
- Channel author and collaborators receive notification

Does the above seem to anyone else like there is a chance to use this interface to make connections?

**Comment by danpia** [comment]
+ for @username 

As for *channel, do you think it would be used in the comments? Or you see it more in use in text blocks? 
It's a fancy feature but I don't see it much as a priority because of the low potential use. It would make more sense if it becomes a complex interface with connections (i.e. adding *channel-name to channel would make automatically a connection instead of a block), just not sure if it's worth go adding and explaining these new paradigms right now.

**Comment by broskoski** [comment]
Yeah, only brought up `*channel` because @dnbrwstr did initially. You're probably right, a good initial step is to concentrate on `@username`.
