### ISSUE TITLE
The close 'x' on search bar loads for a second over the lens icon before hiding

### ISSUE THREAD

**Issue by danpia** [arenahq/ervell#9]
It didn't happen before, it started doing after one of the latest commits

**Comment by broskoski** [comment]
ya, we are gonna have to live with this one for a bit, I just went on a full circle trying to get a good compromise with this, but ended up causing other errors.

**Comment by danpia** [comment]
right now it works fine for me

**Comment by broskoski** [comment]
ah whoops, just seeing this! didn't realize you just closed it :eyes:
