### ISSUE TITLE
https://are.na/ redirects to https://www.are.na/

### ISSUE THREAD

**Issue by msutherl** [arenahq/ervell#96]

**Comment by broskoski** [comment]
Closing, see https://devcenter.heroku.com/articles/apex-domains

**Comment by msutherl** [comment]
@broskoski it's entirely possible via Cloudflare CNAME flattening i.e. http://morgansutherland.com/ is served by Heroku, naked domain works and www redirects

I spent half a day on this a couple months ago :)

**Comment by msutherl** [comment]
there may be issues with https/ssl however per Heroku article, I didn't look into that

**Comment by broskoski** [comment]
It's more this part: 

"Traffic routed over SSL behaves, at the DNS level, identical to unencrypted traffic and suffers from the same naked domain limitations."

I am sure there is a good way to do it, but for now this is the most efficient solution.

**Comment by msutherl** [comment]
gotcha
