### ISSUE TITLE
Only one result in channel connect dropdown

### ISSUE THREAD

**Issue by msutherl** [arenahq/ervell#97]
![screenshot 2015-05-18 12 41 06](https://cloud.githubusercontent.com/assets/31774/7679248/523a791a-fd5b-11e4-9374-52ae3cea042e.png)

Definitely should be multiple results here. Currently can't get the channel I want to connect to pop up in the first spot.

**Comment by msutherl** [comment]
![screenshot 2015-05-20 21 59 47](https://cloud.githubusercontent.com/assets/31774/7735151/9cef3c8e-ff3b-11e4-84e0-62dc705436ee.png)

fixed / won't fix?

**Comment by danpia** [comment]
just pushed (not deployed) a version with 2 results, let's try this

**Comment by msutherl** [comment]
cool thx
